pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.aliyun.com/repository/public' }
    }
}

rootProject.name = "MyApp"
include ':app'
// 新增opencv模块引入，CI自动生成该模块文件夹
include ':opencv'
